CFLAGS = -fPIC -g-pedantic -Wall -Wextra -Werror
LDFLAGS = -shared
CC = gcc

TARGET  = libcomponent.so
SOURCES = libcomponent.c
HEADERS = libcomponent.h
OBJECTS = $(SOURCES:.c=.o)

all: $(TARGET)

clean:
	-rm -f *.o *~ CORE *~
	-rm -f *.so *~ CORE *~

$(TARGET): $(OBJECTS)
	$(CC) -c $(CFLAGS) $(SOURCES)
	$(CC) $(LDFLAGS) -o $@ $<
