CFLAGS = -fPIC -g -pedantic -Wall -Wextra -Werror
LDFLAGS = -shared -fPIC
CC = gcc

TARGET  = libcomponent.so
SOURCES = libcomponent.c
HEADERS = libcomponent.h
OBJECTS = $(SOURCES:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) -c $(CFLAGS) $(SOURCES)
	$(CC) $(LDFLAGS) -o $@ $<

.PHONY: clean
clean:
	-rm -f $(TARGET) $(OBJECTS)
